apiVersion: v1
kind: Namespace
metadata:
  name: palmid
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    pods: "10"
    services: "4"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mylimits
spec:
  limits:
  - max:
      cpu: "500m"
      memory: 500Mi
    min:
      cpu: "100m"
      memory: 100Mi
    type: Pod
  - default:
      cpu: "300m"
      memory: 300Mi
    defaultRequest:
      cpu: "150m"
      memory: 150Mi
    type: Container
